export const actionTypes = {
    SET_LOADER: "SET_LOADER",
    SET_CATEGORY_VALUE: "SET_CATEGORY_VALUE",
    SET_DIFFICULTY_VALUE: "SET_DIFFICULTY_VALUE",
    SET_QUESTION_LIST: "SET_QUESTION_LIST",
    SET_FINAL_RESULT: "SET_FINAL_RESULT",
    SET_SUBMITTED_ANSWERS: "SET_SUBMITTED_ANSWERS",
    RESET_SUBMITTED_ANSWERS: "RESET_SUBMITTED_ANSWERS",
}