export const actionTypes = {
    SET_LOADER: "SET_LOADER",
    SET_CATEGORY_VALUE: "SET_CATEGORY_VALUE",
    SET_DIFFICULTY_VALUE: "SET_DIFFICULTY_VALUE",
    SET_QUESTION_LIST: "SET_QUESTION_LIST",
}