export  const categoryList = [
    { name: "General Knowledge", codeNumber: 9 },
    { name: "Books", codeNumber: 10 },
    { name: "Film", codeNumber: 11 },
    { name: "Music", codeNumber: 12 },
    { name: "Musicals and Theaters", codeNumber: 13 },
    { name: "Television", codeNumber: 14 },
    { name: "Video Games", codeNumber: 15 },
    { name: "Board Games", codeNumber: 16 },
    { name: "Science and Nature", codeNumber: 17 },
    { name: "Computer", codeNumber: 18 },
    { name: "Mathematics", codeNumber: 19 },
    { name: "Mythology", codeNumber: 20 },
    { name: "Sports", codeNumber: 21 },
    { name: "Geography", codeNumber: 22 },
    { name: "History", codeNumber: 23 },
    { name: "Politics", codeNumber: 24 },
    { name: "Art", codeNumber: 25 },
    { name: "Celebrity", codeNumber: 26 },
    { name: "Animals", codeNumber: 27 },
    { name: "Vehicles", codeNumber: 28 },
    { name: "Comics", codeNumber: 29 },
    { name: "Gadgets", codeNumber: 30 },
    { name: "Japanese Anime and Manga", codeNumber: 31 },
    { name: "Cartoon and Animations", codeNumber: 32 },
];